Update test-ci.yml

diff --git a/.github/workflows/test-ci.yml b/.github/workflows/test-ci.yml
--- a/.github/workflows/test-ci.yml
+++ b/.github/workflows/test-ci.yml
@@ -9,73 +9,92 @@ jobs:
     runs-on: ubuntu-latest
     name: test compose action
     steps:
-        - name: Deploy Docker Containers
-        - uses: actions/checkout@v3
-        - uses: isbang/compose-action@v1.5.1
-          with:
-            compose-file: "docker-compose.yml"
-          env:
-            CUSTOM_VARIABLE: "test"
+      - name: Deploy Docker Containers
+      - uses: actions/checkout@v3
+      - uses: isbang/compose-action@v1.5.1
+        with:
+          compose-file: "docker-compose.yml"
+        env:
+          CUSTOM_VARIABLE: "test"
 
-        - name: Install Cypress
-          uses: cypress-io/github-action@v4
-          with:
-            working-directory: ./hippotech-react
-            runTests: false
+      # Cypress tests are very nice, love this framework! However, for sheer speed
+      # we'll use the Jest equivalent, so these steps are now commented out.
 
-        - name: Cypress run
-          uses: cypress-io/github-action@v4
-          with:
-            working-directory: ./hippotech-react
-            install: false
+      - name: Install Cypress
+        uses: cypress-io/github-action@v4
+        with:
+          working-directory: ./hippotech-react
+          runTests: false
 
-        - name: Run Automated Acceptance Tests
-          working-directory: ./jest
-          run: npm install && npm test
-        - name: List Seeker Vulnerabilities
-          if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
-          uses: mtolley/seeker-github-actions/list-seeker-vulnerabilities@v1.1
-          with:
-            seekerAPIToken: ${{ secrets.SEEKER_ACCESS_TOKEN }}
-            minSeverity: HIGH
-            onlySeekerVerified: true
+      - name: Cypress run
+        uses: cypress-io/github-action@v4
+        with:
+          working-directory: ./hippotech-react
+          install: false
 
-        - name: Seeker Compliance Reporting
-          if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
-          uses: mtolley/seeker-github-actions/seeker-compliance-reporting@v1.1
-          with:
-            seekerAPIToken: ${{ secrets.SEEKER_ACCESS_TOKEN }}
-            generateComplianceReportPDF: true
-            failBuildIfNotInCompliance: true
-        - name: Publish Test Report
-          uses: mikepenz/action-junit-report@v3
-          if: success() || failure() # always run even if the previous step fails
-          with:
-            report_paths: 'jest/*.xml'
+      - name: Run Automated Acceptance Tests
+        working-directory: ./jest
+        run: npm install && npm test
+        
+      - name: Remove Java agent
+        if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
+        shell: bash
+        run: |
+          echo "JAVA_TOOL_OPTIONS=" >> $GITHUB_ENV
 
-        - name: Get results from Seeker
-          if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
-          uses: lejouni/seeker-report-export@main
-          with:
-            url: ${{vars.SEEKER_SERVER_URL}}
-            token: ${{secrets.SEEKER_ACCESS_TOKEN}}
-            project: ${{vars.SEEKER_PROJECT_KEY}}
-            format: sarif
-            stacktrace: true
+      - name: List Seeker Vulnerabilities
+        if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
+        uses: mtolley/seeker-github-actions/list-seeker-vulnerabilities@v1.1
+        with:
+          seekerAPIToken: ${{ secrets.SEEKER_ACCESS_TOKEN }}
+          minSeverity: HIGH
+          onlySeekerVerified: true
 
-        - name: Upload SARIF file
-          if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
-          uses: github/codeql-action/upload-sarif@v2
-          with:
+      - name: Seeker Compliance Reporting
+        if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
+        uses: mtolley/seeker-github-actions/seeker-compliance-reporting@v1.1
+        with:
+          seekerAPIToken: ${{ secrets.SEEKER_ACCESS_TOKEN }}
+          generateComplianceReportPDF: true
+          failBuildIfNotInCompliance: true
+
+      # - name: Test Report
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure()
+      #   with:
+      #     name: JEST Tests            
+      #     path: jest/junit.xml    
+      #     reporter: jest-junit        
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'jest/*.xml'
+
+      - name: Get results from Seeker
+        if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
+        uses: lejouni/seeker-report-export@main
+        with:
+          url: ${{vars.SEEKER_SERVER_URL}}
+          token: ${{secrets.SEEKER_ACCESS_TOKEN}}
+          project: ${{vars.SEEKER_PROJECT_KEY}}
+          format: sarif
+          stacktrace: true
+
+      - name: Upload SARIF file
+        if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
+        uses: github/codeql-action/upload-sarif@v2
+        with:
           # Path to SARIF file
-            sarif_file: ${{github.workspace}}/SeekerResults.sarif.json
+          sarif_file: ${{github.workspace}}/SeekerResults.sarif.json
           #sarif_file: samplesarif.json
-          continue-on-error: false
+        continue-on-error: false
 
-        - name: Archive scanning results
-          if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
-          uses: actions/upload-artifact@v3
-          with:
-            name: seeker-analysis-results
-            path: ${{github.workspace}}/SeekerResults.sarif.json
-          continue-on-error: false
+      - name: Archive scanning results
+        if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: seeker-analysis-results
+          path: ${{github.workspace}}/SeekerResults.sarif.json
+        continue-on-error: false
